# Generated by Django 2.2.7 on 2019-12-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('physical_location', models.CharField(max_length=100)),
                ('postal_address', models.CharField(max_length=100)),
                ('contact', models.PositiveSmallIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Institution',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('programme_name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Programme',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('programme_area', models.CharField(max_length=100)),
                ('awarding_institution', models.CharField(max_length=100)),
                ('completion_year', models.PositiveSmallIntegerField()),
                ('appointment_year', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Management',
            },
        ),
        migrations.CreateModel(
            name='Library_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_area', models.CharField(max_length=100)),
                ('book_number', models.PositiveSmallIntegerField()),
                ('book_reference', models.PositiveSmallIntegerField()),
                ('ebook_number', models.PositiveSmallIntegerField()),
                ('audio_visual', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Library_Books',
            },
        ),
        migrations.CreateModel(
            name='Lecture_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('room_description', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Lecture_Room',
            },
        ),
        migrations.CreateModel(
            name='Institution_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Institution_Type',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Lecture_Room')),
            ],
            options={
                'db_table': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='Examination_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Examination_Unit',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('first_name_department_head', models.CharField(max_length=50)),
                ('last_name_department_head', models.CharField(max_length=50)),
                ('other_name_department_head', models.CharField(max_length=50, null=True)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('study_programme', models.CharField(max_length=100)),
                ('awarding_institution', models.CharField(max_length=100)),
                ('completion_year', models.PositiveSmallIntegerField()),
                ('appointment_year', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Contact_Person',
            },
        ),
        migrations.CreateModel(
            name='Business_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('registration_date', models.PositiveSmallIntegerField()),
                ('registration_number', models.PositiveSmallIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Business_Details',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institution')),
            ],
            options={
                'db_table': 'Affiliation',
            },
        ),
    ]
