# Generated by Django 2.2.7 on 2019-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='town',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
