# Generated by Django 2.2.7 on 2019-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191212_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='agency_type',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
