# Generated by Django 2.2.7 on 2019-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_business_details_agency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_type',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
