# Generated by Django 2.2.7 on 2019-12-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20191212_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='physical_location',
        ),
    ]
