# Generated by Django 2.2.7 on 2019-12-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_institution_physical_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_type',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
