# Generated by Django 2.2.7 on 2019-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20191213_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_type',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
