# Generated by Django 2.2.7 on 2019-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20191213_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='registration_date',
            field=models.CharField(max_length=200),
        ),
    ]
