# Generated by Django 2.2.7 on 2019-12-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20191213_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_details',
            name='registration_date',
        ),
    ]
