# Generated by Django 2.2.7 on 2019-12-15 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_business_details_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
