# Generated by Django 2.2.7 on 2019-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20191215_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_type',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
