# Generated by Django 2.2.7 on 2019-12-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
