# Generated by Django 2.2.7 on 2020-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
