# Generated by Django 2.2.7 on 2020-01-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20200130_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='affiliate_level',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='affiliate_programme',
        ),
    ]
