# Generated by Django 2.2.7 on 2020-02-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0027_auto_20200212_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='appointment_year',
        ),
        migrations.RemoveField(
            model_name='management',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='management',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='management',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='management',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='management',
            name='other_name',
        ),
        migrations.AddField(
            model_name='management',
            name='appointment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='management',
            name='name',
            field=models.CharField(default='test', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='qualification',
            field=models.CharField(default='test', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='management',
            name='awarding_institution',
            field=models.CharField(default='test', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='completion_year',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='designation',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='programme_area',
            field=models.CharField(default='test', max_length=100, null=True),
        ),
    ]
