# Generated by Django 2.2.7 on 2020-02-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20200212_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='type',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
    ]
