# Generated by Django 2.2.7 on 2020-02-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_management_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='designation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev')], max_length=50),
        ),
    ]
