# Generated by Django 2.2.7 on 2020-02-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
