# Generated by Django 2.2.7 on 2020-02-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_auto_20200215_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(default='Incompleted', max_length=50, null=True),
        ),
    ]
