# Generated by Django 2.2.7 on 2020-02-17 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0036_auto_20200215_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='institution',
        ),
        migrations.AddField(
            model_name='programme',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
