# Generated by Django 2.2.7 on 2020-02-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_auto_20200217_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='status',
            field=models.CharField(default='incomplete', max_length=50),
        ),
    ]
