# Generated by Django 2.2.7 on 2020-02-17 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0038_programme_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='appointment_year',
            new_name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='awarding_institution',
        ),
        migrations.RemoveField(
            model_name='department',
            name='completion_year',
        ),
        migrations.RemoveField(
            model_name='department',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='department',
            name='study_programme',
        ),
        migrations.AddField(
            model_name='department',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='highest_qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_department_head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
