# Generated by Django 2.2.7 on 2020-02-17 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0039_auto_20200217_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facility',
        ),
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='item_list',
            field=models.CharField(max_length=100),
        ),
    ]
