# Generated by Django 2.2.7 on 2020-02-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0040_auto_20200217_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture_room',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='lecture_room',
            name='room_description',
        ),
        migrations.AddField(
            model_name='lecture_room',
            name='room_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture_room',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
