# Generated by Django 2.2.7 on 2020-02-17 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0041_auto_20200217_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library_books',
            name='institution',
        ),
        migrations.AddField(
            model_name='library_books',
            name='others',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='library_books',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='audio_visual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='book_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='book_reference',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='ebook_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='subject_area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
