# Generated by Django 2.2.7 on 2020-02-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0042_auto_20200217_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(max_length=100, null=True)),
                ('fixed_item', models.CharField(max_length=100, null=True)),
                ('quantity_of_fixed_item', models.PositiveSmallIntegerField(default=0)),
                ('consummable', models.CharField(max_length=100, null=True)),
                ('quantity_of_consummable', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Laboratory',
            },
        ),
    ]
