# Generated by Django 2.2.7 on 2020-02-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0044_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination_unit',
            name='institution',
        ),
        migrations.AddField(
            model_name='examination_unit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
