# Generated by Django 2.2.7 on 2020-02-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_auto_20200217_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='registration_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examination_unit',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='quantity_of_consummable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='quantity_of_fixed_item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='audio_visual',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='book_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='book_reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='ebook_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library_books',
            name='others',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
