# Generated by Django 2.2.7 on 2020-02-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_programme_inst_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='awarding_institution',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='management',
            old_name='programme_area',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='management',
            name='completion_year',
        ),
    ]
