# Generated by Django 2.2.7 on 2020-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0050_auto_20200218_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
