# Generated by Django 2.2.7 on 2020-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0051_auto_20200218_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='qualification',
            new_name='primary_contact',
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(default='incomplete', max_length=50, null=True),
        ),
    ]
