# Generated by Django 2.2.7 on 2020-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0054_auto_20200224_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(default='incomplete', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(default='affiliation', max_length=50, null=True),
        ),
    ]
