# Generated by Django 2.2.7 on 2020-02-25 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0055_auto_20200225_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='establishment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
