# Generated by Django 2.2.7 on 2020-02-26 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_auto_20200226_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='establishment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
