# Generated by Django 2.2.7 on 2020-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_auto_20200226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='establishment_date',
            field=models.CharField(default='incomplete', max_length=50, null=True),
        ),
    ]
