# Generated by Django 2.2.7 on 2020-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_auto_20200226_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='appointment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
