# Generated by Django 2.2.7 on 2020-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0063_auto_20200226_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
