# Generated by Django 2.2.7 on 2020-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0064_auto_20200226_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='establishment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
    ]
