# Generated by Django 2.2.7 on 2020-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0067_auto_20200302_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_head',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution_head',
            name='designation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution_head',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution_head',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
