# Generated by Django 2.2.7 on 2020-03-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_auto_20200302_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='agency_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business_details',
            name='agency_type',
            field=models.CharField(choices=[('RGD', 'Registrar General Department'), ('MMDA', 'Metropolitan, Municipal and District Assemblies'), ('Professional Agency', 'Professional Agency')], max_length=100, null=True),
        ),
    ]
