# Generated by Django 2.2.7 on 2020-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_auto_20200303_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='designation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev')], max_length=50, null=True),
        ),
    ]
