# Generated by Django 2.2.7 on 2020-03-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_auto_20200303_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
